#!/usr/bin/env python

# You'll have to load several libraries into your python environment
# to load the KBase-formatted metabolic model as a CobraPy model: 
# $ pip install cobra
# $ git clone https://github.com/Fxe/cobrakbase
# $ git clone https://github.com/Fxe/ModelSEEDPy
# $ export PYTHONPATH=/home/seaver/Git_Repos/cobrakbase:/home/seaver/Git_Repos/ModelSEEDPy

# The model name is for the one generated by the ../../lib/plant_fba/core/reconstruct_app_impl.py main() function
model_path = "test_model.json"
media_path = "KBaseMedia_PlantAutotrophicMedia.json"

from cobrakbase.core.kbase_object_factory import KBaseObjectFactory
KBOF = KBaseObjectFactory()
kb_model = KBOF.build_object_from_file(model_path, "KBaseFBA.FBAModel")
kb_media = KBOF.build_object_from_file(media_path, "KBaseBiochem.Media")

kb_model.medium = kb_media
solution = kb_model.optimize()
print(solution)
